title: Learn AI - Time Series Forecasting using AML Forecasting Toolkit
description: Microsoft labs for developing a Time Series forecasting solution using AML Forecasting Toolkit.
show_downloads: true
theme: jekyll-theme-cayman
repository: Azure/LearnAI-CustomTimeSeriesForecastingWithAM