title: Learn AI - Building Custom Time Series Forecasting Solutions using AML
description: Microsoft labs for Building Custom Time Series Forecasting Solutions using Azure Machine Learning.
show_downloads: true
theme: jekyll-theme-cayman
repository: Azure/LearnAI-CustomTimeSeriesForecastingWithAML
